name = "preview"
compatibility_date = "2024-06-03"

pages_build_output_dir = "artifacts"

services = [
    { binding = "api", service = "envault-api" },
    { binding = "acheron", service = "acheron-auth" }
]

[vars]
login_dest = "/dashboard"
