name = "envault-api"
compatibility_date = "2024-06-03"

main = "artifacts/main.js"

d1_databases = [
    { binding = "storage", database_name = "envault-db", database_id = "wat" }
]

[build]
command = "pnpm run build/service"
watch_dir = "src"

[vars]
jwt_secret = "supersecretkey"
